name: GitHub Actions Demo
on:
  - pull_request
#on: [push]
#on:
#    push:
#        branches:
#            - master
jobs:
 terraform:
    name: 'Deploy infrastructure'
    #defaults:
    #  run:
    #    shell: bash
    #    working-directory: terraform
        
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
      TF_ACTION_WORKING_DIR: "./terraform"
      TF_VAR_fingerprint:  ${{ secrets.API_FINGERPRINT }}
      TF_VAR_user_ocid:  ${{ secrets.USER_ID }}
      TF_VAR_region: ${{ secrets.REGION}}
      TF_ACTION_WORKSPACE: "default"
            
    #runs-on: [self-hosted, pjuarez]
    runs-on: ubuntu-latest
    
    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "🐧 This job is now running on a ${{ runner.name }} server hosted by GitHub!"
    - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    
    # Checkout the repository to the GitHub Actions runner
    - name: Check out repository code
      uses: actions/checkout@v2
    
    - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
    - run: echo  "The workflow is now ready to test your code on the runner."
    - name: List files in the repository
      run: |
         ls ${{ github.workspace }}
          
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1.3.2
      with:
        terraform_wrapper: false
        
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: 'terraform'
          tf_actions_comment: true
      env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
    
    
