name: Terraform apply scheduled    
on: 
  pull_request:
    types:
      - closed

# schedule:
#   - cron: '15 12 * * *'

#┌───────────── minute (0 - 59)
#│ ┌───────────── hour (0 - 23)
#│ │ ┌───────────── day of the month (1 - 31)
#│ │ │ ┌───────────── month (1 - 12)
#│ │ │ │ ┌───────────── day of the week (0 - 6)
#│ │ │ │ │                                   
#│ │ │ │ │
#│ │ │ │ │
#* * * * *

jobs:
 job1:
    name: 'Terraform Apply'    
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
      TF_VAR_fingerprint:  ${{ secrets.API_FINGERPRINT }}
      TF_VAR_user_id:  ${{ secrets.USER_ID }}
      TF_VAR_region: ${{ secrets.REGION}}
      TF_ACTION_WORKSPACE: "default"
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY}}
    
    steps:

    # Checkout the repository to the GitHub Actions runner
    - name: Check out repository code
      uses: actions/checkout@v2
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1.3.2
      #with:
      #  terraform_wrapper: false
        
      # Configure S3 backend
    - name: Configure S3 backend
      run: | 
        echo  "[default]" > cred_store
        echo "aws_access_key_id= ${{ secrets.access_key_id}}" >> cred_store
        echo "aws_secret_access_key= ${{ secrets.secret_access_key}}" >> cred_store
        cat cred_store
        echo ${{ secrets.secret_access_key}}
        echo ${{ secrets.REGION}}
        
    - name: Terraform Init
      id: init
      run: terraform init
      
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
    
    - name: Terraform apply
      if: github.ref == 'refs/heads/main'
      id: apply
      run: terraform apply -auto-approve  
      
    - uses: actions/github-script@v6
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.TOKEN }}
        script: |
          const output = `#### Terraform apply 📖\`${{ steps.apply.outcome }}\`
    
          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
        
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
          

  
