name: Terraform-Plan

on:
  push:
    branches:
      - master

jobs:
  apply:
    name: Terraform Plan Job

    runs-on:  [self-hosted, pjuarez]
    
    steps:
    - name: Checkout codebase
      uses: actions/checkout@v1

    - name: Terraform - Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        TF_ACTION_WORKING_DIR: 'terraform'
        TF_VAR_fingerprint:  ${{ secrets.API_FINGERPRINT }}
        TF_VAR_user_ocid:  ${{ secrets.USER_ID }}


