name: Terraform-Plan

on:
  push:
    branches:
      - master

jobs:
  apply:
    name: Terraform Plan Job

    runs-on: ubuntu-18.04
    
    steps:
    - name: Checkout codebase
      uses: actions/checkout@v1

    - name: Terraform - Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_ACTION_WORKING_DIR: "./src/iac/providers/github/global"

    - name: Terraform - Plan
      uses: hashicorp/terraform-github-actions/plan@v0.4.0
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ELEVATED_GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: "./src/iac/providers/github/global"
      with:
        args: -var="elevated_github_token=$ELEVATED_GITHUB_TOKEN"
