
name: Deploy Infrastructure

on:
push:
branches:
- master

jobs:
tf_fmt:
name: Deploy Site
runs-on: [self-hosted, pjuarez]

steps:
    - name: Checkout codebase
      uses: actions/checkout@v1
    - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner ${{ runner.name }}."
    - run: echo "🖥️ The workflow is now ready to test your code on the runner."
    - name: List files in the repository
    - run: |
      ls ${{ github.workspace }}

    - name: Terraform - Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_ACTION_WORKING_DIR: "./src/iac/providers/github/global"

    - name: Terraform - Plan
      uses: hashicorp/terraform-github-actions/plan@v0.4.0
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ELEVATED_GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: "./src/iac/providers/github/global"
      with:
        args: -var="elevated_github_token=$ELEVATED_GITHUB_TOKEN"
        

- name: Terraform Init
  uses: hashicorp/terraform-github-actions/init@v0.4.0
  env:
    GITHUB_TOKEN: ${{ secrets.TOKEN }}
    TF_ACTION_WORKING_DIR: 'terraform'
    TF_VAR_fingerprint:  ${{ secrets.API_FINGERPRINT }}
    TF_VAR_user_ocid:  ${{ secrets.USER_ID }}

- name: Terraform Validate
  uses: hashicorp/terraform-github-actions/validate@v0.3.7
