name: Terraform Unit Tests
on: push
jobs:
  go-tests:
    name: Run Terratest Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
 
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1.3.2
     
      - name: Download Go Modules
        working-directory: test
        run: go mod download
      
      - name: Run Go Tests
        working-directory: test
        run: go test -v -tags=unit
    
