name: Terraform Unit Tests
on: push
jobs:
  go-tests:
    name: Run Terratest Unit Tests
    
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
      TF_VAR_fingerprint:  ${{ secrets.API_FINGERPRINT }}
      TF_VAR_user_ocid:  ${{ secrets.USER_ID }}
      TF_VAR_region: ${{ secrets.REGION}}
      TF_ACTION_WORKSPACE: "default"
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCES_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY}}
      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
 
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1.3.2
     
      - name: Download Go Modules
        working-directory: test
        run: go mod download
      
      - name: Run Go Tests
        working-directory: test
        run: go test -v -tags=unit
    
